--
-- create data table `posts`
--

CREATE TABLE `posts` (
  `post_id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `post_name` varchar(30) NOT NULL,
  `post_author` varchar(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- insert data into table `posts`
--
 
INSERT INTO `posts` (`post_id`, `post_name`, `post_author`) VALUES
(1, 'In Otter News: Podcast # 1', 'Ottermin'),
(2, 'In Otter News: Podcast # 2', 'Ottermin'),
(3, 'In Otter News: Podcast # 3', 'Ottermin'),
(4, 'In Otter News: Podcast # 4', 'Ottermin'),
(5, 'In Otter News: Podcast # 5', 'Ottermin'),
(6, 'In Otter News: Podcast # 6', 'Ottermin'),
(7, 'In Otter News: Podcast # 7', 'Ottermin'),
(8, 'In Otter News: Podcast # 8', 'Ottermin'),
(9, 'In Otter News: Podcast # 9', 'Ottermin'),
(10, 'In Otter News: Podcast # 10', 'Ottermin'),
(11, 'In Otter News: Podcast # 11', 'Ottermin'),
(12, 'In Otter News: Podcast # 12', 'Ottermin'),
(13, 'In Otter News: Podcast # 13', 'Ottermin'),
(14, 'In Otter News: Podcast # 14', 'Ottermin'),
(15, 'In Otter News: Podcast # 15', 'Ottermin'),
(16, 'In Otter News: Podcast # 16', 'Ottermin'),
(17, 'In Otter News: Podcast # 17', 'Ottermin'),
(18, 'In Otter News: Podcast # 18', 'Ottermin'),
(19, 'In Otter News: Podcast # 19', 'Ottermin'),
(20, 'In Otter News: Podcast # 20', 'Ottermin'),
(21, 'In Otter News: Podcast # 21', 'Ottermin'),
(22, 'In Otter News: Podcast # 22', 'Ottermin'),
(23, 'In Otter News: Podcast # 23', 'Ottermin'),
(24, 'In Otter News: Podcast # 24', 'Ottermin'),
(25, 'In Otter News: Podcast # 25', 'Ottermin'),
(26, 'In Otter News: Podcast # 26', 'Ottermin'),
(27, 'In Otter News: Podcast # 27', 'Ottermin'),
(28, 'In Otter News: Podcast # 28', 'Ottermin'),
(29, 'In Otter News: Podcast # 29', 'Ottermin'),
(30, 'In Otter News: Podcast # 30', 'Ottermin'),
(31, 'In Otter News: Podcast # 31', 'Ottermin'),
(32, 'In Otter News: Podcast # 32', 'Ottermin'),
(33, 'In Otter News: Podcast # 33', 'Ottermin'),
(34, 'In Otter News: Podcast # 34', 'Ottermin'),
(35, 'In Otter News: Podcast # 35', 'Ottermin'),
(36, 'In Otter News: Podcast # 36', 'Ottermin'),
(37, 'In Otter News: Podcast # 37', 'Ottermin'),
(38, 'In Otter News: Podcast # 38', 'Ottermin'),
(39, 'In Otter News: Podcast # 39', 'Ottermin'),
(40, 'In Otter News: Podcast # 40', 'Ottermin'),
(41, 'In Otter News: Podcast # 41', 'Ottermin'),
(42, 'In Otter News: Podcast # 42', 'Ottermin'),
(43, 'In Otter News: Podcast # 43', 'Ottermin'),
(44, 'In Otter News: Podcast # 44', 'Ottermin'),
(45, 'In Otter News: Podcast # 45', 'Ottermin'),
(46, 'In Otter News: Podcast # 46', 'Ottermin'),
(47, 'In Otter News: Podcast # 47', 'Ottermin'),
(48, 'In Otter News: Podcast # 48', 'Ottermin'),
(49, 'In Otter News: Podcast # 49', 'Ottermin'),
(50, 'In Otter News: Podcast # 50', 'Ottermin'),
(51, 'In Otter News: Podcast # 51', 'Ottermin'),
(52, 'In Otter News: Podcast # 52', 'Ottermin'),
(53, 'In Otter News: Podcast # 53', 'Ottermin'),
(54, 'In Otter News: Podcast # 54', 'Ottermin'),
(55, 'In Otter News: Podcast # 55', 'Ottermin'),
(56, 'In Otter News: Podcast # 56', 'Ottermin'),
(57, 'In Otter News: Podcast # 57', 'Ottermin'),
(58, 'In Otter News: Podcast # 58', 'Ottermin'),
(59, 'In Otter News: Podcast # 59', 'Ottermin'),
(60, 'In Otter News: Podcast # 60', 'Ottermin'),
(61, 'In Otter News: Podcast # 61', 'Ottermin'),
(62, 'In Otter News: Podcast # 62', 'Ottermin'),
(63, 'In Otter News: Podcast # 63', 'Ottermin'),
(64, 'In Otter News: Podcast # 64', 'Ottermin'),
(65, 'In Otter News: Podcast # 65', 'Ottermin'),
(66, 'In Otter News: Podcast # 66', 'Ottermin'),
(67, 'In Otter News: Podcast # 67', 'Ottermin'),
(68, 'In Otter News: Podcast # 68', 'Ottermin'),
(69, 'In Otter News: Podcast # 69', 'Ottermin'),
(70, 'In Otter News: Podcast # 70', 'Ottermin'),
(71, 'In Otter News: Podcast # 71', 'Ottermin'),
(72, 'In Otter News: Podcast # 72', 'Ottermin'),
(73, 'In Otter News: Podcast # 73', 'Ottermin'),
(74, 'In Otter News: Podcast # 74', 'Ottermin'),
(75, 'In Otter News: Podcast # 75', 'Ottermin'),
(76, 'In Otter News: Podcast # 76', 'Ottermin'),
(77, 'In Otter News: Podcast # 77', 'Ottermin'),
(78, 'In Otter News: Podcast # 78', 'Ottermin'),
(79, 'In Otter News: Podcast # 79', 'Ottermin'),
(80, 'In Otter News: Podcast # 80', 'Ottermin'),
(81, 'In Otter News: Podcast # 81', 'Ottermin'),
(82, 'In Otter News: Podcast # 82', 'Ottermin'),
(83, 'In Otter News: Podcast # 83', 'Ottermin'),
(84, 'In Otter News: Podcast # 84', 'Ottermin'),
(85, 'In Otter News: Podcast # 85', 'Ottermin'),
(86, 'In Otter News: Podcast # 86', 'Ottermin'),
(87, 'In Otter News: Podcast # 87', 'Ottermin'),
(88, 'In Otter News: Podcast # 88', 'Ottermin'),
(89, 'In Otter News: Podcast # 89', 'Ottermin'),
(90, 'In Otter News: Podcast # 90', 'Ottermin'),
(91, 'In Otter News: Podcast # 91', 'Ottermin'),
(92, 'In Otter News: Podcast # 92', 'Ottermin'),
(93, 'In Otter News: Podcast # 93', 'Ottermin'),
(94, 'In Otter News: Podcast # 94', 'Ottermin'),
(95, 'In Otter News: Podcast # 95', 'Ottermin'),
(96, 'In Otter News: Podcast # 96', 'Ottermin'),
(97, 'In Otter News: Podcast # 97', 'Ottermin'),
(98, 'In Otter News: Podcast # 98', 'Ottermin'),
(99, 'In Otter News: Podcast # 99', 'Ottermin'),
(100, 'In Otter News: Podcast # 100', 'Ottermin');
